---
title: "Expression Report"
author: "Alfredo Rago"
date: "11/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
library(tidyverse)
library(magrittr)
library(here)
library(SummarizedExperiment)
library(WGCNA)
library(ggrepel)
library(dendextend)
library(DESeq2)
```


```{r import_data, include=T}
# Replace with python input after finalization
gene_data <- here("results/tximeta/gene_data.Rdata") %>% 
  readRDS(.)

abundance_matrix <- 
  assay(gene_data, 2) %>% 
  ceiling(.) %>% 
  vst() %>% 
  t()
```

```{r filter_data}
good_genes <- apply(
  X = abundance_matrix, 
  MARGIN = c(1,2), 
  FUN = function(x){ifelse(x < 6, 0, x)}
) %>% 
  goodSamplesGenes(
    datExpr = ., 
    minNSamples = 2)

summary(good_genes$goodGenes)
summary(good_genes$goodSamples)

abundance_matrix_filtered <- abundance_matrix[,which(good_genes$goodGenes)]

```


```{r PCA, echo=FALSE}
pca_data <- prcomp(x = abundance_matrix_filtered, center = T, scale. = T)
plot(pca_data)

pca_percent_variance <- 
  summary(pca_data) %$% 
  importance[2,] %>% 
  multiply_by(., 100) %>% 
  round(digits = 3) %>% 
  paste0("PC", 1:length(.), " (", ., "% variance)")

odd_samples = 
  which(pca_data$x[,2] < -40) %>% 
  as.integer() 

pca_x <- pca_data$x %>% 
  as_tibble() %>% 
  rownames_to_column(var = "sample_ID")

ggplot(
  data = pca_x, 
  aes(x = PC1, y = PC2, label = sample_ID, col = sample_ID %in% odd_samples)
) + 
  geom_point() +
  geom_text_repel() +
  ggtitle(label = "PCA of samples annotated by gene expression") +
  xlab(label = pca_percent_variance[1]) +
  ylab(label = pca_percent_variance[2]) +
  labs(col = 'Odd Samples')

ggplot(
  data = pca_x, 
  aes(x = PC3, y = PC2, label = sample_ID, col = sample_ID %in% odd_samples)
) + 
  geom_point() +
  geom_text_repel() +
  ggtitle(label = "PCA of samples annotated by gene expression") +
  xlab(label = pca_percent_variance[3]) +
  ylab(label = pca_percent_variance[2]) +
  labs(col = 'Odd Samples')

```

```{r correlation_scatterplot, fig.height=8, fig.width=10, message=FALSE}
library(GGally)

ggpairs(data = pca_x, columns = 2:6, aes(col = sample_ID %in% odd_samples, label = sample_ID), columnLabels = pca_percent_variance[1:5]) + theme_minimal()
```
```{r hclust, echo=FALSE}
expr_hclust <- 
  str_extract(string = row.names(abundance_matrix_filtered), pattern = "[:digit:]{1,2}$") %>% 
  str_pad(string = ., 2, pad = "0") %>% 
  set_rownames(x = abundance_matrix_filtered, value = .) %>% 
  dist(x = ., method = 'euclidean') %>% 
  hclust(d = ., method = 'single')

expr_dend <- as.dendrogram(expr_hclust)
labels_colors(expr_dend) <-
  ifelse(
    labels(expr_dend) %in% str_pad(string = odd_samples, 2, pad = "0"),
    "purple",
    "darkblue"
  )

plot(
  expr_dend,
  main = "Euclidean distance between samples"
)
```
